### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by xan2622** [Anndrey24/VLC_Speed_Controller#2]
Hi Andrei. 
First, thank you for making this very convenient add-on. 👍 I have been looking for such add-on for a long time.

I have made a "mock-up image" to illustrate some UI changes I'd like to see in version 1.2 (if you agree with them of course): 

![9a09](https://user-images.githubusercontent.com/1732773/147968960-87cde0a3-a769-4467-909b-fb8ea4a37b71.png)

1. Move **-** and **+** buttons on the same line as "_Speed:_"

2.  Align the speed value to the right (in the white input box) 

3. Add 6 small buttons with custom speed values (the user would be able to modify these values in the Settings):

![429ac7145(1)](https://user-images.githubusercontent.com/1732773/147888960-20489dbb-7547-4689-b4a6-5fed9d9b256e.png)

4. Add a "Settings" button on the bottom right corner

Thank you in advance for considering to add these changes.

**Comment by Anndrey24** [comment]
Wow, thank you very much for the detailed suggestions! I'll be the first to admit that designing UI isn't my strong suit, so I'll gladly implement your ideas as soon as possible.

**Comment by xan2622** [comment]
Seeing my mock-up makes me think that maybe the "Preferred" button is no longer needed.
After all, if the user can set custom speeds on these 6 buttons, there's a high chance that among all these buttons is the user's preferred speed. That's why I think the "Preferred" button will become useless.

My new mock-up image (now showing 8 custom speeds buttons): 

![4a37b71](https://user-images.githubusercontent.com/1732773/148105461-18c535ce-2a40-438f-8cf5-325ca8c35f5d.png)

**Comment by Anndrey24** [comment]
I added the custom speed buttons and everything seems to be functioning well. However, even after searching everywhere, I wasn't able to find a way to make the default size of the buttons any smaller, so we are stuck with this stretched design unfortunately. The number in the text box can't be aligned to the right either. 
The widget manager seems to be very basic in this regard, not really allowing any customization, but at least the proposed functionality is implemented now.

**Comment by xan2622** [comment]
Thank you for this update! 

About the lack of customization for the buttons width: it's unfortunate. Maybe that is something that should be reported to the VLC developers (hopefully they can allow to change buttons width).

**Comment by Anndrey24** [comment]
It's definitely something that I hope is added for VLC 4. In the meantime, I guess we'll work with what we have. This entire add-on will need to be rebuilt from the ground up once VLC 4 is officially released anyways.

Thanks again for the suggestion!
